## Configuration file to edit messages ##
login:
 usage: "§cUsage: /login <password>"
 authenticated: "§aYou are already authenticated!"
 success: "§aYou have successfully logged in!"
 incorrect: "§cWrong password!"
 not-registered: "§cYou are not registered!"
 
register:
 usage: "§cUsage: /register <password>"
 authenticated: "§aYou are already authenticated!"
 success: "§aYou have successfully registered!"
 registered: "§cYou cannot register twice!"
