name: BukkitAuth
main: net.BukkitAuth.Main
version: "1.0.0"
author: BukkitPE Team
api: ["1.0.0"]

permissions:
 bukkitpelogin.*:
  default: true
  children:
   bukkitpelogin.commands.*:
    default: true
    children:
     bukkitpelogin.commands.login:
      default: true
     bukkitpelogin.commands.register:
      default: true
     bukkitpelogin.commands.manage:
      default: OP